### ISSUE TITLE
Invalid Date 

### ISSUE THREAD

**Issue by sarbbottam** [ta2edchimp/still-alive-app#2]
Looks like some thing is going on with date parsing ...

<img width="465" alt="screen shot 2016-06-27 at 1 18 29 pm" src="https://cloud.githubusercontent.com/assets/949380/16394378/be29830c-3c69-11e6-9369-2f32bc5388eb.png">

**Comment by ta2edchimp** [comment]
Oh yes ... [I really did some bad things to the Date object](https://github.com/ta2edchimp/still-alive-app/blob/master/lib/index.js#L66) :scream:
